# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Francais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Tire', max_length=90)),
                ('contenu', models.TextField(default='Contenu')),
                ('photo', models.ImageField(upload_to='article_photo/')),
                ('editeur', models.CharField(default='Editeur', max_length=50)),
                ('source', models.CharField(default='Source de la nouvelle', max_length=59)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('date_modification', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='web.Category')),
            ],
        ),
    ]
